pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean -DskipTests package -U'
            }
        }
        stage('Test'){
            steps {
                sh 'mvn test pmd:pmd'
                junit 'target/surefire-reports/*.xml'
                pmd canRunOnFailed: true, pattern: 'target/pmd.xml'

            }
        }
        stage('Deploy') {
            steps {
                sh 'ps aux | grep -F BibliothekWS2017Server | grep -v -F 'grep' | awk '{ print $2 }' | xargs kill -9 || true'
                sh 'java -jar ./target/BibliothekWS2017Server-1.0-SNAPSHOT-jar-with-dependencies.jar &'
            }
        }
    }
    post {
        always {
            archive 'target/*.jar, target/*.xml, target/*.properties'
        }
    }
}
