pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean -DskipTests package -U'
            }
        }
        stage('Test'){
            steps {
                sh 'mvn test pmd:pmd'
                junit 'target/surefire-reports/*.xml'
                pmd canRunOnFailed: true, pattern: 'target/pmd.xml'

            }
        }
        stage('Deploy') {
            steps {
                //Deploy application to glassfish
                sh '/opt/glassfish5/glassfish/bin/asadmin --user admin --passwordfile /opt/glassfish5/glassfish/bin/password.txt undeploy BibliothekWS2017Server || true'
                sh './target/BibliothekWS2017Server-1.0-SNAPSHOT-jar-with-dependencies.jar ./target/BibliothekWS2017Server.jar'
                sh '/opt/glassfish5/glassfish/bin/asadmin --user admin --passwordfile /opt/glassfish5/glassfish/bin/password.txt deploy ./target/BibliothekWS2017Server.jar || true'

                //Lines below kills the old jar and starts the new one
                //sh 'echo "nothing to do"'
                //sh 'ps aux | grep -F BibliothekWS2017Server | grep -v -F 'grep' | awk '{ print $2 }' | xargs kill -9 || true'
                //sh 'nohup java -jar ./target/BibliothekWS2017Server-1.0-SNAPSHOT-jar-with-dependencies.jar &'
                //sh 'true'
            }
        }
    }
    post {
        always {
            archive 'target/*.jar, target/*.xml, target/*.properties'
        }
    }
}
